# Default configuration for the training script

# Training parameters
training:
  num_iterations: 1000 # Number of self-play iterations
  num_games_per_iteration: 25 # Number of self-play games per iteration
  num_epochs: 10 # Number of epochs for training the neural network
  batch_size: 32 # Batch size for neural network training
  learning_rate: 0.001 # Initial learning rate
  l2_regularization: 0.0001 # L2 regularization strength
  momentum: 0.9 # Momentum for optimizer
  clip_norm: 10 # Gradient clipping norm
  value_loss_weight: 1.0 # Weight for value loss in total loss
  policy_loss_weight: 1.0 # Weight for policy loss in total loss
  temperature: 1.0 # Temperature for policy distribution during self-play
  dirichlet_alpha: 0.3 # Alpha for Dirichlet noise
  dirichlet_epsilon: 0.25 # Epsilon for Dirichlet noise
  cpu_threads: 8 # Number of CPU threads for data loading

# MCTS parameters
mcts:
  num_simulations: 800 # Number of MCTS simulations per move
  c_puct: 1.0 # PUCT constant
  temp_threshold: 30 # Move number after which temperature is set to 0

# Model parameters
model:
  num_residual_blocks: 19 # Number of residual blocks in the neural network
  num_filters: 256 # Number of filters in convolutional layers
  use_torch_compile: true # Whether to use torch.compile for model optimization

# Checkpointing and logging
checkpointing:
  save_interval: 10 # Save checkpoint every N iterations
  log_interval: 1 # Log training metrics every N epochs
  checkpoint_path: "checkpoints/model.pth" # Path to save/load model checkpoints

# Device configuration
device: "cuda" # Device to use for training (e.g., "cuda" or "cpu")
